# Generated by Django 2.0.5 on 2018-05-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missa',
            name='horarioMissa',
            field=models.CharField(max_length=200),
        ),
    ]
