# Generated by Django 2.0.5 on 2018-05-14 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missas', '0004_diasemana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missa',
            name='diaSemana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missas.diaSemana'),
        ),
    ]
