# Generated by Django 2.0.5 on 2018-05-09 15:24

from django.db import migrations, models
import django.db.models.deletion
import django_thumbs.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Albuns',
                'db_table': 'psssv_album',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('original', django_thumbs.db.models.ImageWithThumbsField(blank=True, null=True, upload_to='galeria')),
                ('dataPublicacao', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.Album')),
            ],
            options={
                'db_table': 'psssv_fotos',
                'ordering': ('album', 'titulo'),
            },
        ),
    ]
