# Generated by Django 2.0.5 on 2018-05-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('paroquia', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner_eventos')),
                ('dataPublicacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
            ],
        ),
    ]
