# Generated by Django 2.0.5 on 2018-05-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='nomeEvento',
            new_name='tituloNoticia',
        ),
    ]
