# Generated by Django 2.0.5 on 2018-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20180514_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner_noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
