# Generated by Django 2.0.5 on 2018-05-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20180514_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
