# Generated by Django 2.0.5 on 2018-05-17 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_auto_20180517_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, max_length=200, unique=True),
        ),
    ]
