# Generated by Django 2.0.5 on 2018-05-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_auto_20180518_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('tituloNoticia',), 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelTable(
            name='noticia',
            table='psssv_noticia',
        ),
    ]
