# Generated by Django 2.0.5 on 2018-05-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_auto_20180518_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='tituloNoticia',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
