# Generated by Django 2.0.5 on 2018-05-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0012_auto_20180518_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={},
        ),
        migrations.AlterModelTable(
            name='noticia',
            table=None,
        ),
    ]
