# Generated by Django 2.0.5 on 2018-05-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0013_auto_20180518_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='banner',
            new_name='imgNoticia',
        ),
    ]
