# Generated by Django 2.0.5 on 2018-05-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('paroquia', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner_eventos')),
            ],
        ),
    ]
